title: Just the Docs Tests
# remote_theme: just-the-docs/just-the-docs@v0.3.3
remote_theme: just-the-docs/just-the-docs@v0.4.0-dev
plugins:
  - jekyll-remote-theme
  - jekyll-default-layout
aux_links:
  Just the Docs Tests on GitHub:
    - //github.com/just-the-docs/just-the-docs-tests
permalink: pretty

collections:
  color:
    output: true
  navigation:
    output: true
  styling:
    output: true
  theme-docs:
    output: true

just_the_docs:
  collections:
    color:
      name: Color Tests
    navigation:
      name: Navigation Tests
      nav_fold: true
    styling:
      name: Styling Tests
      nav_fold: true
    theme-docs:
      name: Theme Docs Tests

defaults:
  -
    scope: {path: "docs/*", type: pages}
    values: {layout: default}
  -
    scope: {type: color}
    values: {layout: default}
  -
    scope: {type: navigation}
    values: {layout: default}
  -
    scope: {type: styling}
    values: {layout: default}
  -
    scope: {type: theme-docs}
    values: {layout: default}
