title: Just the Docs Tests
url: https://just-the-docs.github.io
baseurl: /just-the-docs-tests

theme: just-the-docs

ignore_theme_config: true

plugins:
  - jekyll-default-layout
  - jekyll-include-cache

# ga_tracking: UA-2709176-10,G-5FG1HLH3XQ
# ga_tracking_anonymize_ip: true

# search_enabled: false

aux_links:
  Just the Docs Tests on GitHub:
    - https://github.com/just-the-docs/just-the-docs-tests

nav_external_links:
  - title: This site on GitHub
    url: https://github.com/just-the-docs/just-the-docs-tests
    # hide_icon: true
     
permalink: pretty

gh_edit_link: true
gh_edit_link_text: This page on GitHub
gh_edit_repository: https://github.com/just-the-docs/just-the-docs-tests
gh_edit_branch: main
# gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: tree

# color_scheme: test

compress_html:
  blanklines: true

# compress_html:
#   ignore:
#     envs: all
# 
enable_copy_code_button: true
# 
# kramdown:
#   syntax_highlighter_opts:
#     block:
#       line_numbers: true

collections_dir: collections

collections:
  tests:
    output: true
  accessibility:
    output: true
  color:
    output: true
  components:
    output: true
  customization:
    output: true
  navigation:
    output: true
  search:
    output: true
  styling:
    output: true
  theme-repository:
    output: true
  collection-0:
    output: true
  collection-1:
    output: true
  collection-2:
    output: true

just_the_docs:
  collections:
    tests:
      name: Tests
    accessibility:
      name: Accessibility
      nav_fold: true
    color:
      name: Color
      nav_fold: true
    components:
      name: Components of UI
      nav_fold: true
    customization:
      name: Customization
      nav_fold: true
    navigation:
      name: Navigation
      nav_fold: true
    search:
      name: Search
      nav_fold: true
    styling:
      name: Styling
      nav_fold: true
    theme-repository:
      name: Theme Repository
      nav_fold: true
    collection-0:
      name: Collection 0
    collection-1:
      name: Collection 1
      nav_fold: true
    collection-2:
      name: Collection 2
      nav_fold: true

# jekyll-default-layout doesn't affect pages in collections
defaults:
  -
    scope: {path: "collections/*"}
    values: {layout: default}
  # -
  #   scope: {path: ""}
  #   values: {nav_exclude: true}

# callouts_opacity: 0.15
callouts_level: quiet

callouts:
  admonition:
    # title:
    color: grey-lt
  attention:
    title: Attention
    color: purple
  caution:
    title: Caution
    color: yellow
  danger:
    title: Danger
    color: red
  error:
    title: Error
    color: red
  highlight:
    color: yellow
    opacity: 0.5
  hint:
    title: Hint
    color: grey-dk
  important:
    title: Important
    color: green
  note:
    title: Note
    color: blue
    # color: pink
    opacity: 0.3
  tip:
    title: Tip
    color: grey-dk
  warning:
    title: Warning
    color: red

mermaid:
  # version: "9.4.3"
  # path: "/assets/js/mermaid-9.4.3/mermaid.min.js"
  version: "10.1.0"
  # path: "/assets/js/mermaid-10.1.0/mermaid.esm.min.mjs"
