title: Just the Docs Tests v0.4.0.rc1
url: https://just-the-docs.github.io
baseurl: /just-the-docs-tests

# remote_theme: just-the-docs/just-the-docs@v0.3.3
remote_theme: just-the-docs/just-the-docs@v0.4.0.rc1
# remote_theme: pdmosses/just-the-docs@fix-nav-performance
plugins:
  - jekyll-remote-theme
  - jekyll-default-layout
aux_links:
  Just the Docs Tests on GitHub:
    - https://github.com/just-the-docs/just-the-docs-tests
permalink: pretty

gh_edit_link: true
gh_edit_link_text: This page on GitHub
gh_edit_repository: https://github.com/just-the-docs/just-the-docs-tests
gh_edit_branch: main
# gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: tree

collections_dir: collections

collections:
  tests:
    output: true
  collection-1:
    output: true
  collection-2:
    output: true
  color:
    output: true
  components:
    output: true
  navigation:
    output: true
  search:
    output: true
  styling:
    output: true
  theme-docs:
    output: true

just_the_docs:
  collections:
    tests:
      name: Tests
    color:
      name: Color Tests
    components:
      name: UI Component Tests
      nav_fold: false
    navigation:
      name: Navigation Tests
      nav_fold: true
    search:
      name: Search Tests
      nav_fold: false
    styling:
      name: Styling Tests
      nav_fold: true
    theme-docs:
      name: Theme Docs Tests
    collection-1:
      name: Collection 1
      nav_fold: true
    collection-2:
      name: Collection 2
      nav_fold: true

defaults:
  -
    scope: {path: "collections/*"}
    values: {layout: default}

# callouts_opacity: 0.15
callouts_level: loud

callouts:
  admonition:
    # title:
    color: grey-lt
  attention:
    title: Attention
    color: purple
  caution:
    title: Caution
    color: yellow
  custom:
    title: Custom
    color: pink
    opacity: 0.3
  danger:
    title: Danger
    color: red
  error:
    title: Error
    color: red
  highlight:
    color: yellow
    opacity: 0.5
  hint:
    title: Hint
    color: grey-dk
  important:
    title: Important
    color: green
  note:
    title: Note
    color: blue
  tip:
    title: Tip
    color: grey-dk
  warning:
    title: Warning
    color: red

# mermaid:
#   version: "9.1.3"
